### ISSUE TITLE
VSCode extension doesn't work (TypeSQL Language Server)

### ISSUE THREAD

**Issue by lthi747** [wsporto/typesql#39]
I am using it in a "monorepo" where my db package is located in `./myproject/db` where it also is the `typesql.json` and package.json where the `typesql-cli` is.

The output is (and repeats)

```
node:internal/modules/cjs/loader:1235
  throw err;
  ^

Error: Cannot find module '@libsql/darwin-arm64'
Require stack:
- /Users/lthi747/.vscode/extensions/wsporto.typesql-language-server-0.4.5/node_modules/libsql/index.js
- /Users/lthi747/.vscode/extensions/wsporto.typesql-language-server-0.4.5/server/src/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at requireNative (/Users/lthi747/.vscode/extensions/wsporto.typesql-language-server-0.4.5/node_modules/libsql/index.js:22:10)
    at Object.<anonymous> (/Users/lthi747/.vscode/extensions/wsporto.typesql-language-server-0.4.5/node_modules/libsql/index.js:42:5)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lthi747/.vscode/extensions/wsporto.typesql-language-server-0.4.5/node_modules/libsql/index.js',
    '/Users/lthi747/.vscode/extensions/wsporto.typesql-language-server-0.4.5/server/src/server.js'
  ]
}

Node.js v20.18.1
[Error - 3:58:28 PM] Server process exited with code 1.
[Error - 3:58:29 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 3:58:29 PM] Connection to server got closed. Server will restart.
true
[Error - 3:58:29 PM] TypeSQL Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by wsporto** [comment]
I’ve updated the extension to include the @libsql/darwin-arm64 binary. Could you please verify if this resolves the issue?
